<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Privacy Policy | Radiowatch</title>
    <link rel="stylesheet" href="contact.styles.bootstrap.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="wrapper" style="margin-left: 6%; margin-right: 6%; width: 88%;">
	
	<br />
	<h3>Privacy Policy for Listiary</h3>
	<h5>Last updated: February 27, 2025</h5>
	<br />
	This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.<br /><br />

	<h5>Interpretation</h5>
	The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.<br /><br />

	<h5>Definitions</h5>
	Account means a unique account created for You to access our Service or parts of our Service. Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Listiary. Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. Country refers to Bulgaria. Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. Personal Data is any information that relates to an identified or identifiable individual. Service refers to the Website. Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). Website refers to Listiary, accessible from https://listiary.net/ You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.<br /><br />

	<h5>Personal Data</h5>
	While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to Email addresses.<br /><br />

	<h5>Usage Data</h5>
	Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.<br /><br />

	<h5>Tracking Technologies and Cookies</h5>
	We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.<br /><br />

	<h5>Use of Your Personal Data</h5>
	The Company may use Personal Data for the following purposes:<br />
	To provide and maintain our Service, including to monitor the usage of our Service.<br />
	To manage Your Account: to manage Your registration as a user of the Service.<br />
	To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.<br />
	To provide You with news, special offers and general information about other goods, services and events.<br />
	To manage Your requests: To attend and manage Your requests to Us.<br /><br />

	<h5>Retention of Your Personal Data</h5>
	The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.<br /><br />

	<h5>Transfer of Your Personal Data</h5>
	Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of Your jurisdiction where the data protection laws may differ from those from Your jurisdiction.<br /><br />

	<h5>Delete Your Personal Data</h5>
	You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.<br /><br />

	<h5>Children's Privacy</h5>
	Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under 13.<br /><br />

	<h5>Changes to this Privacy Policy</h5>
	We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.<br /><br />

	<h5>Contact Us</h5>
	If you have any questions about these Terms and Conditions, You can contact us by visiting this page on our website: https://radiowatch.listiary.net/contact/mobile/contact.php <br />
	Generated using TermsFeed Privacy Policy Generator<br /><br />
    </div>    
</body>
</html>